/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'bollywood' : null } |
  { 'generalKnowledge' : null } |
  { 'sports' : null } |
  { 'science' : null };
export type Difficulty = { 'easy' : null } |
  { 'hard' : null } |
  { 'medium' : null };
export interface GameProfile {
  'questionsAnswered' : bigint,
  'name' : string,
  'correctAnswers' : bigint,
  'totalEarnings' : bigint,
}
export interface Question {
  'id' : bigint,
  'difficulty' : Difficulty,
  'questionText' : string,
  'correctAnswerIndex' : bigint,
  'category' : Category,
  'options' : Array<string>,
}
export interface _SERVICE {
  'addQuestion' : ActorMethod<
    [string, Array<string>, bigint, Category, Difficulty],
    undefined
  >,
  'answerQuestion' : ActorMethod<[string, bigint, bigint], boolean>,
  'getAllQuestions' : ActorMethod<[], Array<Question>>,
  'getProfile' : ActorMethod<[string], GameProfile>,
  'getTopPlayers' : ActorMethod<[], Array<GameProfile>>,
  'isUserAlreadyRegistered' : ActorMethod<[string], boolean>,
  'register' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];