/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'bollywood' : IDL.Null,
  'generalKnowledge' : IDL.Null,
  'sports' : IDL.Null,
  'science' : IDL.Null,
});
export const Difficulty = IDL.Variant({
  'easy' : IDL.Null,
  'hard' : IDL.Null,
  'medium' : IDL.Null,
});
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'difficulty' : Difficulty,
  'questionText' : IDL.Text,
  'correctAnswerIndex' : IDL.Nat,
  'category' : Category,
  'options' : IDL.Vec(IDL.Text),
});
export const GameProfile = IDL.Record({
  'questionsAnswered' : IDL.Nat,
  'name' : IDL.Text,
  'correctAnswers' : IDL.Nat,
  'totalEarnings' : IDL.Int,
});

export const idlService = IDL.Service({
  'addQuestion' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Nat, Category, Difficulty],
      [],
      [],
    ),
  'answerQuestion' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getProfile' : IDL.Func([IDL.Text], [GameProfile], ['query']),
  'getTopPlayers' : IDL.Func([], [IDL.Vec(GameProfile)], ['query']),
  'isUserAlreadyRegistered' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'register' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'bollywood' : IDL.Null,
    'generalKnowledge' : IDL.Null,
    'sports' : IDL.Null,
    'science' : IDL.Null,
  });
  const Difficulty = IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'difficulty' : Difficulty,
    'questionText' : IDL.Text,
    'correctAnswerIndex' : IDL.Nat,
    'category' : Category,
    'options' : IDL.Vec(IDL.Text),
  });
  const GameProfile = IDL.Record({
    'questionsAnswered' : IDL.Nat,
    'name' : IDL.Text,
    'correctAnswers' : IDL.Nat,
    'totalEarnings' : IDL.Int,
  });
  
  return IDL.Service({
    'addQuestion' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Nat, Category, Difficulty],
        [],
        [],
      ),
    'answerQuestion' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getProfile' : IDL.Func([IDL.Text], [GameProfile], ['query']),
    'getTopPlayers' : IDL.Func([], [IDL.Vec(GameProfile)], ['query']),
    'isUserAlreadyRegistered' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'register' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };